### ISSUE TITLE
Puppeteer中含$符号的方法如何使用？

### ISSUE THREAD

**Issue by WYQilin** [jae-jae/QueryList-Puppeteer#1]
Puppeteer中的一些函数，含$符号，在php中好像无法使用，求方法。
`$page->$('h1')好像这样不行耶`
如下函数：
page.$(selector)
page.$$(selector)
page.$$eval(selector, pageFunction[, ...args])
page.$eval(selector, pageFunction[, ...args])

**Comment by jae-jae** [comment]
去看这个文档，里面有对`$`的用法说明：https://github.com/nesk/puphpeteer

**Comment by jae-jae** [comment]
- $ => querySelector
- $$ => querySelectorAll
- $x => querySelectorXPath
- $eval => querySelectorEval
- $$eval => querySelectorAllEval

**Comment by WYQilin** [comment]
好的，谢谢大佬
